#!/usr/bin/env bash
# install.sh — one-shot Vigil manager bootstrap.
#
# Runs every step needed to take a fresh checkout to the point where
# `make up` can start the manager. Idempotent: safe to re-run.
#
# What it does:
#   1. Pre-flight: docker, python 3.12+, node 20+ on PATH.
#   2. Bring up the infra stack (Postgres + Redpanda + OpenSearch + Flink).
#   3. Bootstrap Kafka topics.
#   4. Create backend/.venv and install backend deps.
#   5. Generate Python protobuf bindings.
#   6. Generate backend/.env if missing, with secure random secrets.
#   7. Apply database migrations.
#   8. Create the first admin user (random password unless overridden).
#   9. Install frontend deps.
#   10. Print the access URLs + credentials.
#
# Override admin creds via env:
#   VIGIL_ADMIN_EMAIL=admin@example.local
#   VIGIL_ADMIN_PASSWORD='your-password'
#
# Skip steps via env:
#   VIGIL_INSTALL_SKIP_INFRA=1     # don't touch docker compose
#   VIGIL_INSTALL_SKIP_FRONTEND=1  # don't npm install

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$REPO_ROOT"

# ---------- helpers ----------
c_blue=$'\033[0;34m'
c_green=$'\033[0;32m'
c_yellow=$'\033[0;33m'
c_red=$'\033[0;31m'
c_reset=$'\033[0m'
log()   { printf '%s==>%s %s\n' "$c_blue"   "$c_reset" "$*"; }
ok()    { printf '%s==>%s %s\n' "$c_green"  "$c_reset" "$*"; }
warn()  { printf '%s==>%s %s\n' "$c_yellow" "$c_reset" "$*" >&2; }
fatal() { printf '%s==>%s %s\n' "$c_red"    "$c_reset" "$*" >&2; exit 1; }

require() {
    command -v "$1" >/dev/null 2>&1 || fatal "required tool not on PATH: $1"
}

# ---------- 1. pre-flight ----------
log "pre-flight checks"
require docker
require python3
require node
require npm

# Python >= 3.12
py_ver=$(python3 -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")')
case "$py_ver" in
    3.12|3.13|3.14|3.15) : ;;
    3.*) fatal "python 3.12+ required, found $py_ver" ;;
    *)   fatal "python 3.12+ required, found $py_ver" ;;
esac
ok "python $py_ver"

# Node >= 20
node_major=$(node -v | sed 's/^v//' | cut -d. -f1)
[ "$node_major" -ge 20 ] || fatal "node 20+ required, found $(node -v)"
ok "node $(node -v)"

# Docker reachable
docker info >/dev/null 2>&1 || fatal "docker daemon not reachable; start docker first"
ok "docker reachable"

# ---------- 2. infra ----------
if [ -z "${VIGIL_INSTALL_SKIP_INFRA:-}" ]; then
    log "starting infra (postgres / redpanda / opensearch / flink)"
    make infra-up >/dev/null
    log "waiting for postgres + opensearch + redpanda to be healthy"
    # docker compose --wait would be cleaner but isn't on every host.
    deadline=$(( $(date +%s) + 120 ))
    # The compose bootstraps as `postgres` (the cluster superuser); the
    # init script in deploy/postgres-init.sql creates `vigil_manager`
    # as a non-superuser runtime role. Healthcheck talks to `postgres`.
    until docker compose -f deploy/docker-compose.yml exec -T postgres \
              pg_isready -U postgres >/dev/null 2>&1; do
        [ "$(date +%s)" -lt "$deadline" ] || fatal "postgres did not become ready in 120s"
        sleep 2
    done
    ok "postgres ready"
    make infra-bootstrap >/dev/null
    ok "kafka topics bootstrapped"
else
    warn "VIGIL_INSTALL_SKIP_INFRA set; assuming infra is already up"
fi

# ---------- 3. backend venv + deps ----------
log "creating backend venv at backend/.venv"
if [ ! -d backend/.venv ]; then
    python3 -m venv backend/.venv
fi
# shellcheck source=/dev/null
. backend/.venv/bin/activate
python -m pip install --upgrade pip >/dev/null
log "installing backend dependencies (this may take a minute)"
pip install -e 'backend[dev]' >/dev/null
pip install honcho >/dev/null   # process supervisor used by `make up`
ok "backend deps installed"

# ---------- 4. proto bindings ----------
log "regenerating Python protobuf bindings"
make proto-python >/dev/null 2>&1
ok "proto bindings ready"

# ---------- 5. .env ----------
ENV_FILE=backend/.env
if [ ! -f "$ENV_FILE" ]; then
    log "generating backend/.env with random secrets"
    JWT_SECRET=$(python -c 'import secrets; print(secrets.token_hex(32))')
    CA_KEY=$(python -c 'import secrets; print(secrets.token_hex(32))')
    HMAC_KEY=$(python -c 'import secrets; print(secrets.token_hex(32))')
    UPLOAD_KEY=$(python -c 'import secrets; print(secrets.token_hex(32))')
    # M16.a (fixed): vigil_audit_writer is a separate PG role that owns
    # audit_log. The manager's runtime role `vigil_manager` keeps only SELECT +
    # INSERT. The migration creates/rotates this role with the password
    # below; the chain verifier connects through the same DSN.
    AUDIT_OWNER_PASSWORD=$(python -c 'import secrets; print(secrets.token_urlsafe(32))')
    cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# Re-running install.sh does NOT overwrite this file. Delete it first
# if you want a clean reset; expect every existing JWT to be invalid
# and every audit-log row written before that point to fail HMAC
# verification (intentional).
VIGIL_DEBUG=false
VIGIL_PG_DSN=postgresql+asyncpg://vigil_manager:vigil_dev_password@localhost:5432/vigil
VIGIL_PG_DSN_AUDIT=postgresql+asyncpg://vigil_audit_writer:${AUDIT_OWNER_PASSWORD}@localhost:5432/vigil
VIGIL_AUDIT_OWNER_PASSWORD=$AUDIT_OWNER_PASSWORD
VIGIL_OPENSEARCH_URL=http://localhost:9200
VIGIL_KAFKA_BROKERS=localhost:19092
VIGIL_GRPC_LISTEN=0.0.0.0:50051
VIGIL_JWT_SECRET=$JWT_SECRET
VIGIL_CA_MASTER_KEY=$CA_KEY
VIGIL_AUDIT_HMAC_KEY=$HMAC_KEY
VIGIL_UPLOAD_TOKEN_KEY=$UPLOAD_KEY
EOF
    chmod 600 "$ENV_FILE"
    ok "wrote $ENV_FILE (mode 600)"
else
    ok "$ENV_FILE already exists (kept as-is)"
fi

# ---------- 6. db migrations ----------
log "applying database migrations"
# Source the env so VIGIL_AUDIT_OWNER_PASSWORD reaches the M16.a
# (fixed) migration. set -a/+a exports every VAR= line in .env.
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a
( cd backend && alembic upgrade head ) >/dev/null
ok "schema at head"

# ---------- 7. admin user ----------
ADMIN_EMAIL="${VIGIL_ADMIN_EMAIL:-admin@vigil.local}"
ADMIN_PASSWORD="${VIGIL_ADMIN_PASSWORD:-}"
GENERATED_PW=""
if [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD=$(python -c 'import secrets, string; alphabet=string.ascii_letters+string.digits; print("".join(secrets.choice(alphabet) for _ in range(20)))')
    GENERATED_PW=1
fi
log "ensuring admin user exists ($ADMIN_EMAIL)"
admin_status=$(
    cd backend
    python -m scripts.create_admin --email "$ADMIN_EMAIL" --password "$ADMIN_PASSWORD" 2>&1 || true
)
if echo "$admin_status" | grep -q "already exists"; then
    ok "admin user already present (kept existing password)"
    GENERATED_PW=""
elif echo "$admin_status" | grep -q "created admin user"; then
    ok "admin user created"
else
    warn "admin bootstrap returned: $admin_status"
fi

# ---------- 8. frontend ----------
if [ -z "${VIGIL_INSTALL_SKIP_FRONTEND:-}" ]; then
    log "installing frontend dependencies"
    ( cd frontend && npm install --silent ) >/dev/null
    ok "frontend deps installed"
else
    warn "VIGIL_INSTALL_SKIP_FRONTEND set; skipping npm install"
fi

# ---------- 9. summary ----------
mkdir -p .vigil
date -u +"%Y-%m-%dT%H:%M:%SZ" > .vigil/installed

echo
ok "install complete"
echo
echo "  Manager API     http://localhost:8000"
echo "  Frontend (UI)   http://localhost:5173"
echo "  gRPC ingest     localhost:50051 (mTLS)"
echo "  Prometheus      http://localhost:8000/metrics"
echo
if [ -n "$GENERATED_PW" ]; then
    echo "  Admin email     $ADMIN_EMAIL"
    echo "  Admin password  $ADMIN_PASSWORD"
    echo
    warn "Store the admin password now — install.sh does not log it anywhere."
    echo
fi
echo "Next: run \`make up\` to start every backend worker + the frontend."
