//! Device control / USB block (Phase 3 #3.10).
//!
//! Translates a `DeviceControlSyncCmd` into a udev rule installed at
//! `/run/udev/rules.d/99-vigil-device.rules` and reloads udev so the
//! kernel honours it for hot-plug devices. Three policy kinds:
//!
//!   * `usb_block` — default-deny on every `SUBSYSTEM=="usb"` device,
//!     except the operator-listed VID/PID exception pairs which stay
//!     authorised.
//!   * `usb_read_only` — bind `usb-storage`-backed block devices as
//!     read-only via `ATTR{ro}="1"`. Existing mounts aren't remounted
//!     by the rule (Linux doesn't do that retroactively); new mounts
//!     pick up the flag.
//!   * `usb_allow_only` — same shape as `usb_block` but the default is
//!     to deny *unless* the VID/PID pair is on the allow list — this
//!     is the same emitted rule, the distinction is operator-visible.
//!
//! When `enabled=false` the rule file is removed entirely (tombstone).
//!
//! Tests live in `tests/device_control.rs` and re-include this file
//! with `#[path]` so the rule renderer is exercised without writing to
//! `/run/`.

#![cfg(target_os = "linux")]

use agent_core::proto as p;
use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

/// Where the udev rule lives. `/run/udev/rules.d/` is the system path
/// udev itself watches; placing the file in `/etc/udev/rules.d/` would
/// also work but `/run/` makes the rule ephemeral, which matches our
/// "manager is source of truth, agent applies on push" model.
const UDEV_RULE_PATH: &str = "/run/udev/rules.d/99-vigil-device.rules";

/// Render the udev rule body for a policy. Kept pure so the test
/// suite can pin the exact byte string the agent will write.
pub fn render_rule(cmd: &p::DeviceControlSyncCmd) -> String {
    if !cmd.enabled {
        // Tombstone — the apply path removes the file rather than
        // writing this, but we expose the empty body so callers that
        // want a "would-write" preview can render it.
        return String::new();
    }

    let mut out = String::new();
    out.push_str("# Generated by vigil-agent (Phase 3 #3.10). Do not edit.\n");
    out.push_str(&format!("# kind: {}\n", cmd.kind));

    // Same-index VID/PID pairs form an exception. If one list is
    // shorter `zip` truncates to the prefix — extra entries with no
    // counterpart drop out rather than become a sloppy ATTR match.
    match cmd.kind.as_str() {
        "usb_block" | "usb_allow_only" => {
            // Authorise the operator's allowlist first so the
            // default-deny line beneath can't accidentally win on a
            // rule-evaluation reorder.
            for (vid, pid) in cmd.allowed_vids.iter().zip(cmd.allowed_pids.iter()) {
                out.push_str(&format!(
                    "SUBSYSTEM==\"usb\", ATTR{{idVendor}}==\"{vid}\", ATTR{{idProduct}}==\"{pid}\", ATTR{{authorized}}=\"1\"\n",
                ));
            }
            out.push_str(
                "SUBSYSTEM==\"usb\", ENV{DEVTYPE}==\"usb_device\", ATTR{authorized}=\"0\"\n",
            );
        }
        "usb_read_only" => {
            // usb-storage based block devices: flip the `ro` attr so
            // new mounts pick up read-only. The wider USB hierarchy
            // stays authorised — we're only constraining mass-storage.
            out.push_str("SUBSYSTEM==\"block\", ENV{ID_BUS}==\"usb\", ATTR{ro}=\"1\"\n");
        }
        other => {
            // Unknown kind — write a comment so an operator inspecting
            // the file sees what was attempted. Empty enforcement.
            out.push_str(&format!("# unknown kind {other:?}; no rules emitted\n"));
        }
    }
    out
}

/// Apply the policy. Writes (or removes) the rule file, then asks
/// udev to reload + retrigger so plugged-in devices pick up the new
/// authorisation state. `udevadm` is best-effort: if it's missing the
/// rule still lives on disk and udev will read it on its next reload.
pub fn apply(cmd: &p::DeviceControlSyncCmd) -> Result<()> {
    apply_at(cmd, Path::new(UDEV_RULE_PATH))
}

/// Test-friendly entry point. Takes an explicit rule path so the
/// integration test can target a tempdir.
pub fn apply_at(cmd: &p::DeviceControlSyncCmd, rule_path: &Path) -> Result<()> {
    if !cmd.enabled {
        // Tombstone — remove the file. Missing-is-OK; another concurrent
        // apply may have already cleaned it.
        match std::fs::remove_file(rule_path) {
            Ok(()) => {
                tracing::info!(
                    kind = %cmd.kind,
                    path = %rule_path.display(),
                    "device_control.rule_removed",
                );
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => {
                return Err(e).with_context(|| format!("remove {}", rule_path.display()));
            }
        }
        let _ = reload_udev();
        return Ok(());
    }

    let body = render_rule(cmd);
    write_atomic(rule_path, &body)?;
    tracing::info!(
        kind = %cmd.kind,
        vid_count = cmd.allowed_vids.len(),
        pid_count = cmd.allowed_pids.len(),
        path = %rule_path.display(),
        "device_control.rule_written",
    );
    if let Err(e) = reload_udev() {
        // Reload failure is non-fatal — the next udev event picks it
        // up. Log so an operator notices a half-applied state.
        tracing::warn!(error = %e, "device_control.udevadm_failed");
    }
    Ok(())
}

fn write_atomic(path: &Path, body: &str) -> Result<()> {
    let parent: PathBuf = path
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));
    std::fs::create_dir_all(&parent).with_context(|| format!("mkdir -p {}", parent.display()))?;
    let tmp = parent.join(format!(
        ".{}.tmp",
        path.file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| "device-control".into())
    ));
    std::fs::write(&tmp, body).with_context(|| format!("write {}", tmp.display()))?;
    std::fs::rename(&tmp, path).with_context(|| format!("rename to {}", path.display()))?;
    Ok(())
}

fn reload_udev() -> Result<()> {
    use std::process::{Command as Proc, Stdio};
    let r1 = Proc::new("udevadm")
        .args(["control", "--reload"])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .with_context(|| "spawn udevadm control --reload")?;
    if !r1.success() {
        anyhow::bail!("udevadm control --reload exited {:?}", r1.code());
    }
    let r2 = Proc::new("udevadm")
        .args(["trigger"])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .with_context(|| "spawn udevadm trigger")?;
    if !r2.success() {
        anyhow::bail!("udevadm trigger exited {:?}", r2.code());
    }
    Ok(())
}
