"""Pydantic schemas for the Phase 4 #4.1 AI surfaces.

Three shapes:

  * ``AlertSummaryOut`` — projection of the ``alert_summary`` row the
    analyst UI consumes via ``GET /api/alerts/{id}/summary``.
  * ``NlQueryRequest`` / ``NlQueryResponse`` — wire shape for the
    natural-language → KQL/Lucene translator at
    ``POST /api/ai/nl-to-query``.

The suggested-response array is left as ``list[dict]`` rather than
typed entries: the prompt's vocabulary will evolve in follow-up
tuning passes, and pinning the action kinds in the schema would make
each tuning round a Pydantic breaking change. The widget renders
entries it recognises and ignores the rest.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field

from app.schemas.common import ORMModel


class AlertSummaryOut(ORMModel):
    id: UUID
    alert_id: UUID
    tenant_id: UUID
    summary: str
    suggested_response_json: list[dict] | None
    model_id: str
    cached_input_tokens: int
    output_tokens: int
    created_at: datetime


class NlQueryRequest(BaseModel):
    # Operator-typed English. 1024 chars matches the model's prompt
    # budget; longer prompts get rejected at the API boundary rather
    # than silently truncated in the SDK.
    prompt: str = Field(min_length=1, max_length=1024)
    # KQL and Lucene only — Sigma YAML is generated by hand or via the
    # sigma rule pack, not via natural language.
    language: Literal["kql", "lucene"] = "lucene"


class NlQueryResponse(BaseModel):
    query: str
    language: Literal["kql", "lucene"]
    # Carried through verbatim from the wrapper so an operator who
    # cares about prompt-cache efficiency can audit it inline in dev
    # tools without hitting the admin metrics endpoint.
    cached_input_tokens: int = 0
    output_tokens: int = 0
    model_id: str


__all__ = ["AlertSummaryOut", "NlQueryRequest", "NlQueryResponse"]
